name: Test for PR on develop branch

on:
  pull_request:
    branches:
      - 'develop'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn

      - name: remove build directory
        run: rm -rf ./build

      - name: Build 
        run: yarn run build

      - name: lint
        run: yarn run lint

  commit-check:
    name: commit check
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3.5.2
        with: 
          fetch-depth: 0

      - name: check squash
        run: ./.github/scripts/check-squash.sh
        shell: bash

      - name: check commit message
        run: ./.github/scripts/check-commit-message.sh
        shell: bash

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0

    - name: run docker gitleaks
      run: docker run -v `pwd`:/path zricethezav/gitleaks:latest detect --source="/path" --verbose